# config/data.yaml

# 1) Eğitim, doğrulama ve test görüntü klasörleri
train: ../dataset_last/train/images
val:   ../dataset_last/valid/images
test:  ../dataset_last/test/images

# 2) Sınıf sayısı
nc: 23

# 3) Sınıf isimleri (0’dan 22’ye sıralı)
names:
  0: ada_etrafinda_donunuz
  1: dur
  2: durak
  3: girisi_olmayan_yol
  4: iki_yonlu_yol
  5: ileri_mecburi
  6: ileri_ve_saga_mecburi
  7: ileri_ve_sola_mecburi
  8: ileriden_saga_mecburi
  9: isikli_isaret_cihazi
  10: kirmizi_isik
  11: park_yasak
  12: park_yeri
  13: saga_donulmez
  14: saga_mecburi
  15: sagdan_gidiniz
  16: sola_donulmez
  17: sola_mecburi
  18: soldan_gidiniz
  19: tunel
  20: yaya_gecidi
  21: yesil_isik
  22: yol_ver
